name: Check Syntax

on:
  push:
    branches:
      - check_syntax

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # Optionally, you can specify a version range for pip
          pip-version: latest

      - name: Update pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Install flake8
        run: |
          pip install flake8

      - name: Display Python version
        run: |
          python --version

      - name: Run flake8
        run: |
          flake8

