# Nazwa workflow
name: check_syntax

# Wywołaj workflow po dodaniu pusha na gałąź 'check_syntax'
on:
  push:
    branches:
      - 'check_syntax'

# Definicja zadania 
jobs:
  check_syntax:
    runs-on: ubuntu-latest
    
    # Strategia macierzy do uruchomienia zadania w różnych wersjach pythona
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    
    steps:
      # Pobranie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Konfiguracja wersji Pythona
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #  Aktualizacja narzędzia pip
      - name: Update pip
        run: pip install -U pip

      # Instalacja flake8
      - name: Install flake8
        run: python -m pip install flake8

      # Wyświetlenie wersji Pythona
      - name: Display Python version
        run: python -V

      # Uruchomienie flake8 
      - name: Run flake8
        run: flake8 zad2.py
