name: hello

on: [workflow_dispatch]
     
jobs:
  hello:

    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

    
