name: hello

on: [workflow_dispatch]
     
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5
       with:
         python-version: '3.10'  


    
